server:
  port: 8081
spring:
  application:
    name: hmdp
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://vm2.lan.luoxianjun.com:3306/hmdp?useSSL=yes&serverTimezone=UTC
    username: luo
    password: I_4f2_FWPY_tQYb7
  redis:
    host: vm2.lan.luoxianjun.com
    port: 6379
    password: password123456
    lettuce:
      pool:
        max-active: 10
        max-idle: 10
        min-idle: 1
        time-between-eviction-runs: 10s
  jackson:
    default-property-inclusion: non_null # JSON处理时忽略非空字段
  servlet:
    multipart:
      max-file-size: 10MB
mybatis-plus:
  type-aliases-package: com.hmdp.entity # 别名扫描包
logging:
  level:
    com.hmdp: debug

minio:
  endpoint: https://minio.lan.luoxianjun.com
  accessKey: wLr3WyH7QRkYbmVs83HH
  secretKey: hgAwbBTGD2wcLmDCklVPIibK1qSg2F4V81pCiq11

